travis:
  secure:
    BINSTAR_TOKEN: hdrpRiCI1INRTWBIuSqRnR4ndeV8xt7dt+En2Wr8qHUI6xe2A0ccQ0SHYC4NNTLNc8QT+qGod908255KUw9gksTamrUxCAoqwumevfnpafbr4Gp+V1tpUWJpWUHFh1chE1LELkGpPslotFw351QyXRpNJOE0JOEjITrlbJgOd6FVQeRNjDHFGnS8tPAyoFwEMQSFsK7SwVWL0qYbAKdozhcpEhoxyGrT/XjSsEG71j9VlOYAICnXshb1gCuBaIy8Q8jItSfY4IWwBs52CGt1UxT+O8YZV+0PBfmDUdeUFGu1qucGZbZAFP3MC0lcfOZsGmX5lYkKBTxWrnCv5/iH2hO0TSK4SVJi/nbqk4tdObyhV3nyPt+duFIdvor8Z6iChsB/pGpSIicsx9Rw8mNUXQqg7vEgynZTDN1DxtPGCz1TC5mYcqg4tyd4CEm3/ocjY99Czu0S9FkQ4QgCLLRo1FXSa00mSA2bsAPK2GQJGEljlVdEUsLg07MIUuiMlD0DN/az8pkM2Ul0PkBblWSnr2wzVFz8EVz2hq9cBKj5DddT3Me7nIPnRPeGuO2iwshbYM3n5pfcfGgCOKcbK1GP/b7fM4Yow7foOLCYCBYwrv/ifqPmWLpWtJkYJgfd82LewsWRwt8O04K39/KS/gR1QMVflaGiXSxA60ZAC+KyVbM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
